[package]
name = "work-escrow"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
multiversx-sc = "0.54.0"
shared-types = { path = "../shared-types" }

[dev-dependencies]
multiversx-sc-scenario = "0.54.0"
